In [1]:
import numpy as np

a = np.array([[2, 4], [6, 8]])

In [2]:
# digite 'a.' + <tab> para lista de metodos
print(a.mean())
print(a.diagonal())
print(a.ndim)

5.0
[2 8]
2


# Exemplo da eficiência de NumPy

In [3]:
soma = 0
for i in range(1, 100000001):
    soma += i
print(soma)

5000000050000000


In [4]:
np.arange(1, 100000001).sum()

987459712

# Slicing Arrays

In [5]:
l = [20, 30, 10, 40]
print(l[1:3])
print(l[::2]) # passo 2

[30, 10]
[20, 10]


In [6]:
a = np.array(l)
a

array([20, 30, 10, 40])

In [7]:
print(a[1:3])
print(a[::2])

[30 10]
[20 10]


In [8]:
l2 = l[:] # copia da lista 'l'
l2

[20, 30, 10, 40]

In [9]:
l2[0] = 1000
print(l)
print(l2)

[20, 30, 10, 40]
[1000, 30, 10, 40]


In [10]:
a

array([20, 30, 10, 40])

In [11]:
b = a[:] # não copia array 'a'
b

array([20, 30, 10, 40])

In [12]:
b[0] = 1000
print(a)
print(b)

[1000   30   10   40]
[1000   30   10   40]


In [13]:
b[:] = 42
a

array([42, 42, 42, 42])

In [14]:
c = a.copy() # efetua cópia de array
print(c)
print(a)

[42 42 42 42]
[42 42 42 42]


In [15]:
c[0] = 10000
print(c)
print(a)

[10000    42    42    42]
[42 42 42 42]


# Matrizes

In [16]:
mat = [[5, 4, 7], [0, 3, 4], [0, 0, 6]]
for linha in mat:
    print(linha)
print('-' * 10)
print(mat[0])
print(mat[-1])
print('-' * 10)
print(mat[1][1])

[linha[1] for linha in mat]

[5, 4, 7]
[0, 3, 4]
[0, 0, 6]
----------
[5, 4, 7]
[0, 0, 6]
----------
3


[4, 3, 0]

# Criando matrizes com NumPy

In [17]:
import numpy as np

In [18]:
joao_pts = [20, 30, 40, 15]
pedro_pts = [100, 24, 48, 23]
maria_pts = [92, 22, 34, 12]
anderson_pts = [12, 34, 12, 43]

pontos = np.array([joao_pts, pedro_pts, maria_pts, anderson_pts])
pontos

array([[ 20,  30,  40,  15],
       [100,  24,  48,  23],
       [ 92,  22,  34,  12],
       [ 12,  34,  12,  43]])

In [19]:
# acessando uma linha da matriz
pontos[0]

array([20, 30, 40, 15])

In [20]:
# acessando elemento pelos indices
pontos[1][0]

100

In [21]:
# gerando array com 20 elementos de 0 a 19
my_data = np.arange(0, 20)
print(my_data)
print(my_data[5])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
5


In [23]:
# tranformando array em matriz
mat1 = np.reshape(my_data, (5, 4))
print(mat1)
mat1

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [24]:
# acessando elemento pelos indices
mat1[2][2]

10

In [25]:
pontos

array([[ 20,  30,  40,  15],
       [100,  24,  48,  23],
       [ 92,  22,  34,  12],
       [ 12,  34,  12,  43]])

In [26]:
# acessando elemento pela posição
pontos.item(5)

24

In [27]:
m1 = ['python', 'é', 'legal']
m2 = ['guido', 'van', 'rossum']
m3 = [10, 20, 30]
[m1, m2, m3]

[['python', 'é', 'legal'], ['guido', 'van', 'rossum'], [10, 20, 30]]

In [28]:
np.array([m1, m2, m3])

array([['python', 'é', 'legal'],
       ['guido', 'van', 'rossum'],
       ['10', '20', '30']], dtype='<U6')

# Operaçõe com matrizes

In [29]:
import numpy as np

In [30]:
m1 = np.array([[1,2,3],[4,5,6]])
m2 = np.array([[7,8,9],[10,11,12]])

In [31]:
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
m2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [33]:
# dividindo uma matriz por outra
m2 / m1

array([[7. , 4. , 3. ],
       [2.5, 2.2, 2. ]])

In [34]:
# arredondando valores
np.matrix.round(m2/m1)

array([[7., 4., 3.],
       [2., 2., 2.]])

In [35]:
# multiplicando elementos da matriz por k
10 * m2

array([[ 70,  80,  90],
       [100, 110, 120]])

In [36]:
# somando/subtraindo elementos da matriz por k
m1 + 5

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [37]:
# subtraindo elementos da matriz por k
m2 - 1

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [38]:
# multiplicando matrizes
m1 * m2

array([[ 7, 16, 27],
       [40, 55, 72]])

In [39]:
# elevando os elementos da matriz à potência k
m1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)