In [2]:
import numpy

In [4]:
a = numpy.array([10, 20, 30, 40])
a

array([10, 20, 30, 40])

In [5]:
type(a)

numpy.ndarray

In [11]:
# criando matriz 2 X 2
mat = numpy.array([[1, 2], [3, 4]])
mat

array([[1, 2],
       [3, 4]])

In [15]:
print(mat[1][1])
print(mat[-1][-1])

4
4


In [20]:
# seleção de linhas da matriz
print(mat[0,:]) # 1ª linha
print(mat[1,:]) # 2ª linha

[1 2]
[3 4]


In [23]:
# seleção de colunas da matriz
print(mat[:,0]) # 1ª coluna
print(mat[:,1]) # 2ª coluna

[1 3]
[2 4]


In [26]:
# matriz transposta
mat.transpose()

array([[1, 3],
       [2, 4]])

In [39]:
m1 = numpy.array([[1, 2], [3, 4]])
m2 = numpy.array([[5, 6], [7, 8]])
m1 + m2

array([[ 6,  8],
       [10, 12]])

In [38]:
m2 - m1

array([[4, 4],
       [4, 4]])

In [37]:
m1 * m2

array([[ 5, 12],
       [21, 32]])

In [35]:
m3 = numpy.array([1, 2, 3, 4])
m3.sum()

10

In [33]:
# indice do maior valor do array
m3.argmax()

3

In [36]:
# indice do menor valor do array
m3.argmin()

0