# Inserindo elementos no array

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [3]:
np.insert(arr, 1, 10 )

array([ 1, 10,  2,  3])

In [5]:
a = np.array([[1, 2], [3, 4]])
print(a)
print(a.ndim)

[[1 2]
 [3 4]]
2


In [6]:
print(a.sum(axis=0))

[4 6]


In [8]:
print(a.sum(axis=1))

[3 7]


In [9]:
np.insert(a, 1, 5, axis=1)

array([[1, 5, 2],
       [3, 5, 4]])

In [11]:
np.insert(a, 0, 5, axis=0)

array([[5, 5],
       [1, 2],
       [3, 4]])

## Anexando valores no final do array

In [12]:
# append
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [14]:
np.append(a, [4,5,6])

array([1, 2, 3, 4, 5, 6])

In [18]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [20]:
np.append(a, [[5,6]])

array([1, 2, 3, 4, 5, 6])

In [22]:
np.append(a, [[5,6]], axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
# atenção ao número de elementos da dimensão
np.append(a, [[5,6,7]], axis=0)

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [25]:
# atenção ao número de dimensões
np.append(a, [5,6,7], axis=0)

ValueError: all the input arrays must have same number of dimensions

## Deletando elementos do array

In [26]:
import numpy as np

In [27]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
np.delete(a, 1, axis=0)

array([[1, 2],
       [5, 6]])

In [30]:
np.delete(a, 0, 1)

array([[2],
       [4],
       [6]])

In [31]:
a = np.array([[1,2,3], [4,5,6],[7,8,9],[10,11,12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [33]:
np.delete(a, np.s_[::2], axis=0)

array([[ 4,  5,  6],
       [10, 11, 12]])

In [35]:
np.delete(a, np.s_[::2], axis=1)

array([[ 2],
       [ 5],
       [ 8],
       [11]])

## Repetindo elementos de um array

In [36]:
import numpy as np

In [37]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [38]:
np.repeat(a, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [39]:
np.repeat(a, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [40]:
np.repeat(a, 2, axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [41]:
np.repeat(a, 2, 1) # axis=1

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [42]:
np.repeat(3, 4)

array([3, 3, 3, 3])

## Repetindo array com tile

In [43]:
import numpy as np

In [44]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [45]:
np.tile(a, 2)

array([1, 2, 3, 1, 2, 3])

In [46]:
np.tile(a, 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [47]:
b = np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [51]:
np.tile(b, 2)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

## Dividindo um array

In [52]:
import numpy as np

In [53]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
np.array_split(a, 2, axis=0)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [55]:
np.array_split(a, 2, axis=1)

[array([[1, 2],
        [4, 5]]), array([[3],
        [6]])]

In [56]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [57]:
arrays = np.array_split(b, 2, axis=0)
arrays

[array([[1, 2, 3],
        [4, 5, 6]]), array([[ 7,  8,  9],
        [10, 11, 12]])]

In [58]:
for array in arrays:
    print(array)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


## Criando arrays de zeros e ums

In [59]:
import numpy as np

In [60]:
np.zeros(4)

array([ 0.,  0.,  0.,  0.])

In [61]:
np.zeros((2,2))

array([[ 0.,  0.],
       [ 0.,  0.]])

In [62]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [63]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [64]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [66]:
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [69]:
np.ones((10,10))

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

## Criando uma matriz identidade 
#### Matriz quadrada com elementos da diagonal principal iguais a 1 e demais elementos iguais a 0.

In [70]:
import numpy as np

In [71]:
d = np.eye(2)
d

array([[ 1.,  0.],
       [ 0.,  1.]])

In [72]:
np.eye(10)

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

## Indexação booleana

In [73]:
import numpy as np

In [75]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [76]:
a[a>3]

array([4, 5, 6])

In [77]:
a[a>1]

array([2, 3, 4, 5, 6])

In [78]:
a[a<4]

array([1, 2, 3])

In [79]:
idx = (a > 2)
idx

array([[False, False],
       [ True,  True],
       [ True,  True]], dtype=bool)