# Carregando dados do arquivo com NumPy

In [1]:
import numpy as np

In [3]:
val1, val2, val3 = np.loadtxt('../../curso_python/datasets/dados.txt', skiprows=1, unpack=True)
print(val1)
print(val2)
print(val3)

[ 0.1212  0.104   0.5661  0.762 ]
[ 0.842     0.5422    0.932     0.847361]
[ 0.3672   0.34551  0.2344   0.1538 ]


In [5]:
my_array = np.genfromtxt('../../curso_python/datasets/dados_faltantes.txt', skip_header=1, filling_values=-999)
print(my_array)

[[  1.21200000e-01   8.42000000e-01   3.67200000e-01]
 [ -9.99000000e+02   5.42200000e-01   3.45510000e-01]
 [  5.66100000e-01   9.32000000e-01  -9.99000000e+02]
 [  7.62000000e-01   8.47361000e-01   1.53800000e-01]]


## Juntando uma sequência de arrays

In [6]:
import numpy as np

In [12]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])

In [13]:
a

array([[1, 2],
       [3, 4]])

In [14]:
b

array([[5, 6]])

In [17]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
b.T

array([[5],
       [6]])

In [26]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

## Embaralhando uma sequência

In [27]:
import numpy as np

In [29]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
# embaralhando in place(no prórpio array)
np.random.shuffle(a)
a

array([3, 8, 9, 2, 7, 1, 4, 5, 0, 6])

## Números complexos com NumPy

In [33]:
import numpy as np

In [36]:
a = np.array([1, 10 + 2j, 20 + 5j], dtype=complex)
a

array([  1.+0.j,  10.+2.j,  20.+5.j])

In [37]:
a[1]

(10+2j)

In [38]:
a[2]

(20+5j)

In [39]:
a[1] + a[2]

(30+7j)

In [40]:
a[1] - a[2]

(-10-3j)

## Gerando arrays com linspace

In [41]:
import numpy as np

In [42]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [43]:
np.arange(1, 100, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [44]:
np.linspace(2.0, 3.0)

array([ 2.        ,  2.02040816,  2.04081633,  2.06122449,  2.08163265,
        2.10204082,  2.12244898,  2.14285714,  2.16326531,  2.18367347,
        2.20408163,  2.2244898 ,  2.24489796,  2.26530612,  2.28571429,
        2.30612245,  2.32653061,  2.34693878,  2.36734694,  2.3877551 ,
        2.40816327,  2.42857143,  2.44897959,  2.46938776,  2.48979592,
        2.51020408,  2.53061224,  2.55102041,  2.57142857,  2.59183673,
        2.6122449 ,  2.63265306,  2.65306122,  2.67346939,  2.69387755,
        2.71428571,  2.73469388,  2.75510204,  2.7755102 ,  2.79591837,
        2.81632653,  2.83673469,  2.85714286,  2.87755102,  2.89795918,
        2.91836735,  2.93877551,  2.95918367,  2.97959184,  3.        ])

In [45]:
np.linspace(2.0, 3.0, 5)

array([ 2.  ,  2.25,  2.5 ,  2.75,  3.  ])

In [46]:
np.linspace(2.0, 2.5, 5)

array([ 2.   ,  2.125,  2.25 ,  2.375,  2.5  ])

## Encontrando elementos únicos de um array

In [47]:
import numpy as np

In [48]:
a = np.array([[1,2],[2,3],[3,3],[4,4]])
a

array([[1, 2],
       [2, 3],
       [3, 3],
       [4, 4]])

In [49]:
np.unique(a)

array([1, 2, 3, 4])

## Lendo arquivos CSV com NumPy

In [50]:
import numpy as np

In [56]:
valores = np.genfromtxt('../../curso_python/datasets/arquivo.csv', delimiter=';', skip_header=1)
valores

array([[ 10.,  20.,  30.],
       [ 40.,  50.,  60.],
       [ 70.,  80.,  90.],
       [ 34.,  54.,  23.]])